### ISSUE TITLE
When to release your code？

### ISSUE THREAD

**Issue by xhding1997** [iustinsirbu13/multimodal-ssl-for-disaster-tweet-classification#1]
Thanks for your excellent work, you have done a good job!
When to release your code and data? I'm waiting for it.

**Comment by iustinsirbu13** [comment]
Hi there, thank you for your kind words!
Sorry for making you wait, I will make sure to upload everything by next week.
Thank you for the reminder and appreciation!

**Comment by iustinsirbu13** [comment]
Hi again,
The code is now uploaded. Feel free to experiment with it and let me know if you encounter any difficulties.

**Comment by xhding1997** [comment]
> Hi again, The code is now uploaded. Feel free to experiment with it and let me know if you encounter any difficulties.

Thanks for your reply, I will try it at free time.
